config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :payments, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batch_log.rb
class BatchLog < ApplicationRecord
end

app/models/consumer.rb
class Consumer < ApplicationRecord
  has_many :consumer_billings, dependent: :destroy
  has_one :consumer_credit, dependent: :destroy
  has_one :consumer_debt, dependent: :destroy
  has_many :consumer_transactions, dependent: :destroy
end

app/models/consumer_billing.rb
class ConsumerBilling < ApplicationRecord
  has_many :consumertransactions, dependent: :destroy
  has_many :consumer_credits, dependent: :destroy
  has_one :receipt, dependent: :destroy
  belongs_to :consumer
end

app/models/consumer_credit.rb
class ConsumerCredit < ApplicationRecord
  has_many :consumer_offset_events, dependent: :destroy
  belongs_to :consumer_billing, optional: true
  belongs_to :consumer_transaction, foreign_key: 'consumer_transaction_id', optional: true
  belongs_to :consumer
end

app/models/consumer_debt.rb
class ConsumerDebt < ApplicationRecord
    belongs_to :consumer
    belongs_to :receipt
    has_many :consumer_offset_events, dependent: :destroy
end

app/models/consumer_offset_event.rb
class ConsumerOffsetEvent < ApplicationRecord
  belongs_to :consumer_credit
  belongs_to :consumer_debt
end

app/models/consumer_transaction.rb
class ConsumerTransaction < ApplicationRecord
  belongs_to :consumer
  belongs_to :consumer_billing, optional: true
  has_one :consumer_debt, dependent: :destroy
  has_one :consumer_credit, dependent: :destroy
end

app/models/payment.rb
class Payment < ApplicationRecord
    validates :amount, presence: true
    validates :payment_time, presence: true
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :consumer_billing
  has_one :consumer_debt, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.payment_time = Time.current  # 現在時刻を設定
    if @payment.save
      redirect_to payment_path(@payment), notice: '入金が完了しました。'
    else
      render :new, alert: '入金に失敗しました。もう一度お試しください。'
    end
  end

  def show
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:amount, :payment_time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PathToAtone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/new.html.erb
<h1>入金</h1>
<%= form_with model: @payment, local: true do |form| %>
  <div>
    <%= form.label :amount, '入金金額' %>
    <%= form.number_field :amount %>
  </div>
  <div>
    <%= form.submit '入金する' %>
  </div>
<% end %>

app/views/payments/show.html.erb
<h1>入金確認</h1>
<p>入金金額: <%= @payment.amount %>円</p>
<p>入金日: <%= @payment.payment_time %></p>
<%= link_to '入金画面に戻る', new_payment_path, class: 'btn btn-primary' %>